# Generated by Django 3.0.3 on 2020-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='site_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_ip', models.GenericIPAddressField()),
                ('location', models.CharField(max_length=20)),
                ('site_address', models.CharField(max_length=50)),
                ('spoc_name1', models.CharField(max_length=20)),
                ('spoc_contact1', models.CharField(max_length=13)),
                ('spoc_name2', models.CharField(max_length=20)),
                ('spoc_contact2', models.CharField(max_length=13)),
            ],
            options={
                'db_table': 'site_details',
            },
        ),
        migrations.CreateModel(
            name='vip_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_ip', models.GenericIPAddressField()),
                ('virtual_ip', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'vip_details',
            },
        ),
    ]
