# Generated by Django 2.2.7 on 2020-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='virtual_server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_ip', models.GenericIPAddressField()),
                ('virtual_ip', models.GenericIPAddressField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'virtual_server',
            },
        ),
        migrations.DeleteModel(
            name='vip_details',
        ),
        migrations.AlterField(
            model_name='site_details',
            name='spoc_contact1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='site_details',
            name='spoc_contact2',
            field=models.CharField(max_length=20),
        ),
    ]
