# Generated by Django 2.2.7 on 2020-03-30 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='handover_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function', models.CharField(choices=[('RAVPN', 'RAVPN'), ('DNS', 'DNS'), ('CDC Devices', 'CDC Devices')], default='RAVPN', max_length=20)),
                ('incident_ticket', models.CharField(blank=True, max_length=20)),
                ('vendor_ticket', models.CharField(blank=True, max_length=20)),
                ('problem_statement', models.CharField(blank=True, max_length=50)),
                ('summary', models.CharField(blank=True, max_length=100)),
                ('submitted_by', models.CharField(blank=True, max_length=20)),
                ('assigned_to', models.CharField(blank=True, max_length=20)),
                ('submitted_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'handover_details',
            },
        ),
    ]
