# Generated by Django 2.2.7 on 2020-03-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover_details',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed')], default='Active', max_length=10),
        ),
    ]
