# Generated by Django 2.2.7 on 2020-04-02 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0002_handover_details_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover_details',
            name='last_updated_by',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='handover_details',
            name='last_updated_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='handover_details',
            name='submitted_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
