# Generated by Django 2.2.7 on 2020-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0003_auto_20200402_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='handover_details',
            name='resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='handover_details',
            name='last_updated_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='handover_details',
            name='submitted_date',
            field=models.DateTimeField(),
        ),
    ]
