# Generated by Django 2.2.7 on 2020-04-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0004_auto_20200408_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover_details',
            name='summary',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
