# Generated by Django 2.2.7 on 2020-04-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0006_auto_20200408_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover_details',
            name='resolution',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='handover_details',
            name='summary',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
