# Generated by Django 2.2.7 on 2020-05-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handover_form', '0008_auto_20200411_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handover_details',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
